language: node_js

node_js:
  - "8.9.4"

sudo: true

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE db_venta_albumes_test;CREATE USER venta_albumes WITH ENCRYPTED PASSWORD '1234';GRANT ALL PRIVILEGES ON DATABASE db_venta_albumes_test TO venta_albumes;"
  - node_modules/.bin/sequelize db:migrate
